dtb-$(CONFIG_ARCH_MXC) += kontron-samx8x-dx.dtb \
			  kontron-samx8x-dx-m4.dtb \
			  kontron-samx8x-dxp.dtb \
			  kontron-samx8x-dxp-m4.dtb \
			  kontron-samx8x-qxp.dtb \
			  kontron-samx8x-qxp-m4.dtb
